language: java
install:
  - ./resources/library/install_local_jars_linux.sh
  - mvn validate -B -V
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
